Feature/welcome screen
BrightCoders-Proyectos/covid-tracker pull request #10
Opened 2020-09-04 17:46 UTC by xErikPsx

# Description
Implementing the Welcome screen.
 - I've made the design for the app and placed a dummy image.
  
  ## Screenshots 
![image](https://user-images.githubusercontent.com/26925761/92271008-aea42500-eeac-11ea-9801-b6197bab27f8.png)

2020-09-04 18:06 UTC, cfcortes commented
@xErikPsx SonarCloud ys reporting one code smell which is really easy to fix!

2020-09-04 18:39 UTC, OwenRamire requested changes

2020-09-04 18:39 UTC, OwenRamire commented on src/screens/Welcome.js
> +      /> */}
Don't forget to erase the things that you are not going to use

2020-09-04 18:39 UTC, OwenRamire commented on src/screens/Welcome.js
> +    height: '100%',
height is not necessary because you are using `flex: 1` and that property will give you all the space on the screen

2020-09-04 18:39 UTC, OwenRamire commented on src/screens/Welcome.js
> +    width: '80%',
Try to use more the flex property instead of a percentage, and maybe you won't need to use the height and width properties

2020-09-04 18:39 UTC, OwenRamire commented on src/screens/Welcome.js
> +          source={require('../utils/example-covid.png')}
Put this image in another folder like `src/assets/images`

2020-09-04 23:48 UTC, OwenRamire approved these changes

2020-09-09 16:31 UTC, luisarmandodv approved these changes

2020-09-09 19:00 UTC, merged