Feature/account screen
BrightCoders-Proyectos/covid-tracker pull request #13
Opened 2020-09-15 19:28 UTC by OwenRamire

# Account Screen layout
Closes #4
- Create the account screen layout
- Create the new navigation to arrive at the Account screen
- Use the `secureTextEntry` into the TextInput components where the users will type their passwords

  ## Screenshots 
![navigationIntoAccount](https://user-images.githubusercontent.com/42794917/93254907-bbebca00-f75e-11ea-9d95-9cbd76a6fce7.gif)

![Screenshot_1600196030](https://user-images.githubusercontent.com/42794917/93253345-61ea0500-f75c-11ea-8037-059652d2eba9.png)

![Screenshot_1600196017](https://user-images.githubusercontent.com/42794917/93255002-dcb41f80-f75e-11ea-9fb7-5599de6b8062.png)

2020-09-15 19:52 UTC, LeyaimMagma requested changes

2020-09-15 19:52 UTC, LeyaimMagma commented on src/screens/RegisterAccount.js
> +            <Text style={styles.nextBtnText}>Siguiente</Text>
could you create a file with the constant for all the text?
like export const NEXT_MESSAGE_ES = 'Siguiente';

2020-09-15 19:52 UTC, LeyaimMagma commented on src/screens/RegisterAccount.js
> +          </View>
Could you refactor this? try using a custom hook or a component

2020-09-15 22:27 UTC, LeyaimMagma requested changes

2020-09-15 22:27 UTC, LeyaimMagma commented on src/screens/RegisterAccount.js
> +            title="Escribe de nuevo la clave"
can you add this text on Constants.js?

2020-09-15 22:27 UTC, LeyaimMagma commented on src/screens/RegisterAccount.js
> +            isRequired="Requerido"
can you add this text on Constants.js?
IS_REQUIRED = "Requerido"

2020-09-15 22:27 UTC, LeyaimMagma commented on src/components/PasswordRequirements.js
> +        </Text>
add these texts on Constants.js?

2020-09-16 15:59 UTC, LeyaimMagma approved these changes, later dismissed

2020-09-16 23:44 UTC, xErikPsx approved these changes
Well changed!

2020-09-16 23:49 UTC, LeyaimMagma approved these changes

2020-09-16 23:53 UTC, merged