Feature/code confirmation screen
BrightCoders-Proyectos/covid-tracker pull request #18
Opened 2020-09-28 15:54 UTC by OwenRamire

# Create the code confirmation screen layout
Close #6 
## Description
- Create the layout of the screen 
- Read the value on the TextInput components
- Clean the form if the user touches the button "Enviar código de nuevo"
- Create the code "1234" to test the screen if the user types the correct code, the incorrect code and if the user doesn't type the code

  ## Screenshots 
- Screen layout: 
![Screenshot_1601077944](https://user-images.githubusercontent.com/42794917/94454072-0ade2a00-0177-11eb-8fe9-c683d5f29b4e.png)

- Type the correct code: 
![CodeConfirmationSuccess](https://user-images.githubusercontent.com/42794917/94454151-20ebea80-0177-11eb-9041-6be1bf36ad31.gif)

- Type the incorrect code:
![CodeConfirmationWrong](https://user-images.githubusercontent.com/42794917/94454569-a2437d00-0177-11eb-8131-be158b59e624.gif)

- Touch the button "Siguiente" without type the code confirmation:
![CodeConfirmationEmpty](https://user-images.githubusercontent.com/42794917/94454689-cacb7700-0177-11eb-9e0f-de3271bae7ea.gif)

2020-09-28 21:03 UTC, xErikPsx submitted a review, later dismissed
Everything looks okay Owen, nice!

2020-09-29 17:17 UTC, luisarmandodv requested changes

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +      formData.fieldFour === ''
You could use `some()` js function. 
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/some

```suggestion
      formData.some(value => value !== '');
```

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +      let userCodeConfirmation = [
`userCodeConfirmation` could be a constant if you are not modifying its value.

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +      ];
You could use js destructuration
```suggestion
      let userCodeConfirmation = [
        ...formData
      ];
```

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +      }
This is good, but always try to use `forEach` or `map()` in order to make interactions cleaner

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +          />
This code is being repeated, make a function where you iterate and return that JSX.

2020-09-29 17:17 UTC, luisarmandodv commented on src/screens/ConfirmEmail.js
> +export default ConfirmEmail;
is this component `ConfirmEmail` completely reusable? its children's can be splited in other reusable components.

2020-09-29 17:18 UTC, luisarmandodv commented
Your commits are pretty well written! Congrats!!

2020-09-30 23:28 UTC, luisarmandodv approved these changes

2020-10-01 19:49 UTC, xErikPsx approved these changes
This looks pretty nice! Good job!

2020-10-01 22:01 UTC, merged