Feature/15 contact information screen
BrightCoders-Proyectos/covid-tracker pull request #19
Opened 2020-10-06 19:08 UTC by OwenRamire

close #15 
# Description
- Create the "Información de Contacto" screen layout
- Create a new component that stores the instructions of what the user is going to do on the screen 
-  Reuse the EmailPassTxtInput component where the user will type his name and his phone. Also, using props we tell at this component what keyboard we need on each input. 
- Create new navigation until this new screen

## Screenshots 
- Layout of the screen

![Screenshot_1602009892](https://user-images.githubusercontent.com/42794917/95248594-25e71480-07dd-11eb-82d5-2adee4ffe03a.png)

- using the default keyboard on the "Nombre" input
![Screenshot_1602009904](https://user-images.githubusercontent.com/42794917/95248690-47e09700-07dd-11eb-8136-b3adc5ffba17.png)

- using the phone-pad keyboard on the "Teléfono" input
![Screenshot_1602009918](https://user-images.githubusercontent.com/42794917/95248734-5f1f8480-07dd-11eb-984d-a2c92498c3ae.png)

2020-10-06 20:07 UTC, xErikPsx reviewed
Cool design! Approved!

2020-10-06 20:08 UTC, xErikPsx submitted a review, later dismissed

2020-10-06 20:52 UTC, fernandoamz requested changes

2020-10-06 20:52 UTC, fernandoamz commented on src/components/DescContactInfo.js
> +        cuando sea necesario
Add a constant  folder into `src` and create a constants file import the text as variable

2020-10-06 20:52 UTC, fernandoamz commented on src/navigations/NavigationLogin.js
> +        name="ContactInformation"
```suggestion
        name='ContactInformation'
```

2020-10-06 20:52 UTC, fernandoamz commented on src/screens/ContactInformation.js
> +            isRequired="Recomendado"
```suggestion
            isRequired='Recomendado'
```

change all double-quotes for simple-quotes on the files

2020-10-06 20:52 UTC, fernandoamz commented on src/screens/ContactInformation.js
> +        <Text style={styles.title}>Información de Contacto</Text>
Add all the texts as constants

2020-10-07 18:11 UTC, fernandoamz approved these changes

2020-10-07 22:31 UTC, luisarmandodv approved these changes

2020-10-07 22:59 UTC, merged

2020-10-08 19:41 UTC, xErikPsx reviewed
It looks on point!