Feature/create account form validation
BrightCoders-Proyectos/covid-tracker pull request #21
Opened 2020-10-08 20:51 UTC by xErikPsx

# Description
The porpuse of this PR is to make easier to track some issues that I'm having with it. It will be changed.

2020-10-09 19:16 UTC, cfcortes commented
@xErikPsx on PRs Description you must specify or explain the purpose of the intention of your contibution (coder), this is why or what you have implemented and submitted.

I understand that in this case, you submitted your PR so others could have a look at your code and help you. Still should have described your PR, and perhaps you could have added a note or an additional note asking for help t other (mentors).

I think you can still edit your description. I so, please add it.

2020-10-09 20:05 UTC, xErikPsx commented
I just tried to upload the PR as soon as I could because Aramando was answering me quickly and I wanted to him checked asap because I know their busy too. But of course, I will edit my PR review.

2020-10-09 22:26 UTC, luisarmandodv requested changes

2020-10-09 22:26 UTC, luisarmandodv commented on src/screens/RegisterAccount.js
> +          } else {|
```suggestion
          } else {
```

2020-10-09 22:26 UTC, luisarmandodv commented on src/screens/RegisterAccount.js
> +            setColor({...color, passwordInput: false, fourthdTerm: false});
```suggestion
            setColor({...color, passwordInput: false, fourthTerm: false});
```

2020-10-09 22:26 UTC, luisarmandodv commented on src/screens/RegisterAccount.js
> +  };
```suggestion
  const validateOnPasswords = () => {
    const { lengthPassword, lowerCase, caps, number } = validatePasswords(
      data.password,
      data.validatePassword,
    );

    const passwordInput = !lengthPassword || !lowerCase || !caps || !number || !(data.password === data.validatePassword);
    
    setColor({
      ...color,
      passwordInput,
      firsTerm: !lengthPassword,
      secondTerm: !lowerCase,
      thirdTerm: !caps,
      fourthTerm: !number
    });

    return passwordInput;
  };
```

2020-10-29 23:07 UTC, OwenRamire approved these changes, later dismissed
🚀

2020-10-29 23:44 UTC, luisarmandodv requested changes
Remember to use PropTypes on ALL the components

https://es.reactjs.org/docs/typechecking-with-proptypes.html

2020-10-29 23:44 UTC, luisarmandodv commented on src/components/PasswordRequirements.js
> +    // color: Colors.red
```suggestion
```

2020-10-29 23:44 UTC, luisarmandodv commented on src/components/PasswordRequirements.js
> +const PasswordRequirements = (props) => {
```suggestion
const PasswordRequirements = (props) => {
  const keyItemsArray = ['firstTerm', 'secondTerm', 'thirdTerm', 'fourthTerm'];

  return keyItemsArray.map( key => {
    const color = props[key] ? Colors.red : Colors.black;
    const text = PASS_REQUIREMENTS[key];
    return (
      <Text style={[styles.textInfo, {color}]} key={key}>
        <Text style={styles.dash}>- </Text>
        {text}
      </Text>
      )
    )
  };
```

2020-10-29 23:44 UTC, luisarmandodv commented on src/components/PasswordRequirements.js
> +const PasswordRequirements = (props) => {
All that function, can be refactored to this

2020-10-29 23:44 UTC, luisarmandodv commented on src/screens/RegisterAccount.js
> +        console.log('Exito');
```suggestion
```

2020-10-29 23:44 UTC, luisarmandodv commented on src/screens/RegisterAccount.js
> +    console.log('validateOnPasswords -> lengthPassword', lengthPassword);
```suggestion
```

2020-10-30 00:20 UTC, fernandoamz requested changes

2020-10-30 00:20 UTC, fernandoamz commented on src/screens/RegisterAccount.js
> +        console.log('Sin exito');
```suggestion
return
```

2020-10-30 00:20 UTC, fernandoamz commented on src/screens/RegisterAccount.js
>              title="Correo electrónico"
Add to constant file

2020-10-30 00:20 UTC, fernandoamz commented on src/screens/RegisterAccount.js
>              title="Clave"
Add to constant file

2020-11-02 18:20 UTC, LeyaimMagma requested changes

2020-11-02 18:20 UTC, LeyaimMagma commented on src/components/PasswordRequirements.js
> +  const fourthTermWrong = props.fourthTerm ? Colors.red : Colors.black;
You can refactor this and create a function

2020-11-11 21:10 UTC, luisarmandodv approved these changes

2020-11-11 22:37 UTC, LeyaimMagma approved these changes

2020-11-11 22:44 UTC, LeyaimMagma approved these changes

2020-11-12 17:29 UTC, merged