Feature/16 sign in screen
BrightCoders-Proyectos/covid-tracker pull request #22
Opened 2020-10-13 21:04 UTC by OwenRamire

# Description
- This new form is for the users that they were registered before, and they want to use his account 
- In case that the user touches the button "Iniciar sesión" and doesn't have an account, this form has a button called "¿No tienes cuenta? Regístrate" that will send the user into the SignUp forms.

# Screenshots 
- Layout of the screen

![Screenshot_1602617340](https://user-images.githubusercontent.com/42794917/95907961-f5195900-0d61-11eb-9b57-90e9e3d7807f.png)

- Go SignIn screen

![GoSignIn](https://user-images.githubusercontent.com/42794917/95908099-272abb00-0d62-11eb-85a8-a3168162d167.gif)

- Go SignUp forms from SignIn screen

![GoSignUpOnSignIn](https://user-images.githubusercontent.com/42794917/95908222-5e996780-0d62-11eb-9914-3ad304b53a6a.gif)

2020-10-13 21:43 UTC, fernandoamz requested changes

2020-10-13 21:43 UTC, fernandoamz commented on src/navigations/NavigationSignIn.js
> +          title: 'Inicio de sesión',
Add to constants file

2020-10-13 21:43 UTC, fernandoamz commented on src/screens/signInScreens/SignIn.js
> +            title="Correo electrónico"
Add to constants file

2020-10-13 21:43 UTC, fernandoamz commented on src/screens/signInScreens/SignIn.js
> +      }
```suggestion
      } 
      
      return <EmailPassTxtInput key={type} title="Clave" password={true} />;
```

2020-10-13 22:40 UTC, xErikPsx requested changes
The mentor Fernando left some comments, those could be cool to change.

2020-10-14 14:34 UTC, fernandoamz commented
@xErikPsx, Sorry, I didn't see this name of the screen `NavigationSignIn` I think that is better if you choose a better name without the `Navigation` prefix this will be redundant in the next screens.

2020-10-14 20:06 UTC, fernandoamz requested changes

2020-10-14 20:06 UTC, fernandoamz commented on src/screens/signInScreens/SignIn.js
> +    return inputs;
```suggestion
    return inputType.map((type) => {
        if (type === EMAIL) {
          return <EmailPassTxtInput key={type} title={EMAIL} password={false} />;
        }
        return <EmailPassTxtInput key={type} title={PASSWORD} password={true} />;
    });
```

2020-10-14 21:10 UTC, fernandoamz approved these changes

2020-10-15 17:24 UTC, luisarmandodv approved these changes

2020-10-15 21:47 UTC, merged