Create Register Completed Screen
BrightCoders-Proyectos/covid-tracker pull request #26
Opened 2020-10-19 19:41 UTC by xErikPsx

# Description

- New Register Completed Screen.
- There's no functionallity in "Iniciar" button until the incoming issues.
 
  ## Screenshots 

![image](https://user-images.githubusercontent.com/26925761/96503535-01e1f500-1219-11eb-8dc8-629fef0fae69.png)

closes

2020-10-19 21:10 UTC, OwenRamire requested changes

2020-10-19 21:10 UTC, OwenRamire commented on src/screens/RegisterCompleted.js
> +  succesContainer: {
Add the "s" on the `succesContainer` (`successContainer`) property and also in the component where you use this property

2020-10-19 21:10 UTC, OwenRamire commented on src/screens/Welcome.js
> +            navigation.navigate('RegisterCompleted');
I assume that when you navigate into the `RegisterCompleted` screen, you navigate when the  user put his contact information like this screen not when the user touches the "Iniciar sesión" button 

![image](https://user-images.githubusercontent.com/42794917/96511551-d9f88e80-1224-11eb-8f97-4575d52dbcd8.png)

2020-10-19 21:10 UTC, OwenRamire commented on src/screens/RegisterCompleted.js
> +
Delete all the white spaces that you have

2020-10-19 21:10 UTC, OwenRamire commented on src/screens/RegisterCompleted.js
> +            </Text>
Put the text in a constant message on the file `src/utils/constants` and import them

2020-10-26 17:25 UTC, OwenRamire requested changes

2020-10-26 17:25 UTC, OwenRamire commented on src/screens/RegisterCompleted.js
>        <View style={styles.succesContainer}>
Change `styles.succesContainer` for `styles.successContainer`

2020-11-13 20:13 UTC, OwenRamire submitted a review, later dismissed
🚀

2020-11-13 20:40 UTC, luisarmandodv requested changes

2020-11-13 20:40 UTC, luisarmandodv commented on src/screens/RegisterCompleted.js
> +
```suggestion
```

2020-11-13 20:40 UTC, luisarmandodv commented on src/screens/RegisterCompleted.js
> +
```suggestion
```

2020-11-13 20:40 UTC, luisarmandodv commented on src/screens/RegisterCompleted.js
> +
```suggestion
```

2020-11-13 20:40 UTC, luisarmandodv commented on src/screens/RegisterCompleted.js
> +          <Text style={styles.textBtnAccept}>Iniciar</Text>
I see you already have a constant file for text. Could you add this text to that file?

2020-11-13 23:04 UTC, luisarmandodv approved these changes

2020-11-13 23:16 UTC, OwenRamire approved these changes

2020-11-13 23:17 UTC, merged