Feature/privacy policy screen
BrightCoders-Proyectos/covid-tracker pull request #9
Opened 2020-09-03 22:14 UTC by OwenRamire

# Privacy Policy screen
Closes #3
This is the layout of the privacy policy screen.
The screen has a ScrollView in case that the Privacy Policy is long 
![Screenshot_1599168988](https://user-images.githubusercontent.com/42794917/92178080-5c5cf880-ee07-11ea-87e1-2b3cfcd9a7e1.png)

![Screenshot_1599168992](https://user-images.githubusercontent.com/42794917/92178084-5d8e2580-ee07-11ea-823c-e90f911bb003.png)

2020-09-03 22:41 UTC, xErikPsx approved these changes
Nice changes, everything looks cool!

2020-09-08 20:58 UTC, luisarmandodv requested changes

2020-09-08 20:58 UTC, luisarmandodv commented on src/screens/PrivacyPolicy.js
> +        <>
is this necessary?

2020-09-09 16:30 UTC, luisarmandodv approved these changes

2020-09-09 19:34 UTC, xErikPsx approved these changes
Everything looks cool!

2020-09-11 22:31 UTC, cfcortes approved these changes

2020-09-11 22:33 UTC, luisarmandodv approved these changes

2020-09-11 22:34 UTC, merged